title: "Ohsung Kwon — Portfolio"
description: "CAE/MBD & NVH simulation, e-powertrain, and engineering projects"
url: "https://oskwon9278.github.io"
baseurl: ""

# YAT theme (remote_theme)
remote_theme: "jeffreytse/jekyll-theme-yat"

# GitHub Pages plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# pagination settings
paginate: 10
paginate_path: "/page:num/"

# site settings
header_pages:
  - about.md
  - projects.md

# author information
author:
  name: "Ohsung Kwon"
  email: "oskown9278@gmail.com" 
  github: ""
  linkedin: "https://www.linkedin.com/in/oskwon9278/" 

# YAT options
yat:
  date_format: "%b %d, %Y"
  show_categories: true
  show_tags: true
  open_graph: true

# build base
timezone: "America/New_York"
markdown: kramdown